### ISSUE TITLE
Drill files not shown correct

### ISSUE THREAD

**Issue by Phreak87** [attie/webgerber#2]
Hi, 

i tried to open my drill file exported from KiCad.
But i have only one line with all drills at y:0.

the failed function in drillfiles is getNum. 
Replace this function with this:

```
            function getNum(offset) {
                var r = /^[-+\d\.?\d*?]*/.exec(d = d.slice(offset)); // assert(r);
				var numLEN = numVal(r[0]);
                d = d.slice(String(numLEN).length);
                return numLEN
            }
```

and drill files works perfectly in my case.

**Comment by attie** [comment]
Hi @Phreak87 , thanks for the report.

This isn't my code, but I'm happy to accept fixes!
Are you able to share the drill file that demonstrates the issue?

**Comment by Phreak87** [comment]
Sure,

[CNC-PTH.zip](https://github.com/attie/webgerber/files/3685712/CNC-PTH.zip)
Please Test If this Works with your Files too

**Comment by Phreak87** [comment]
This one is also Important:

String(numLEN).length
The lenght from Direct to String Casting is different ...

**Comment by attie** [comment]
Oh, it worked for me without... (using your example file)

Could you confirm here? https://attie.github.io/webgerber/

I would have expected `String(numLEN).length` to be more problematic than `r[0].length`, as the positive sign will likely be dropped, etc...

**Comment by attie** [comment]
e.g:

![image](https://user-images.githubusercontent.com/2195519/66312236-303fab80-e908-11e9-93ac-be9a4953303f.png)
